//- ----------------------------------------------------------------------------------------------------------------------
//- load libraries -------------------------------------------------------------------------------------------------------
#include <AS.h>                                                         // the asksin framework
#include "hardware.h"                                                   // hardware definition
//#include <cmDimmer.h>
#include <cmSwitch.h>

//- stage modules --------------------------------------------------------------------------------------------------------
AS hm;                                                                  // asksin framework

cmSwitch cmSwitch[6];                                                 // create instances of channel module 
//cmDimmer cmDimmer[2];  
extern void initIt(uint8_t channel);                                   // declare function to jump in
extern void switchIt(uint8_t channel, uint8_t status, uint8_t characteristic);
extern void switchIt2(uint8_t channel, uint8_t status);
uint8_t bTemperature; 

//- ----------------------------------------------------------------------------------------------------------------------
//- eeprom defaults table ------------------------------------------------------------------------------------------------
uint16_t EEMEM eMagicByte;
uint8_t  EEMEM eHMID[3]  = {0x60,0x60,0x60,};
uint8_t  EEMEM eHMSR[10] = {'X','M','S','7','2','3','4','5','6','8',};
uint8_t  EEMEM eHMKEY[16] = {0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x10,};

// if HMID and Serial are not set, then eeprom ones will be used
uint8_t HMID[3] = {0x60,0x60,0x60,};
uint8_t HMSR[10] = {'X','M','S','7','2','3','4','5','6','8',};          // XMS1234567
uint8_t HMKEY[16] = {0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x10,};


//- ----------------------------------------------------------------------------------------------------------------------
//- generated by createRegisterFromFile.pl
//- ID: 0x00b8, File: rf_dim_2l_644.xml
//- ----------------------------------------------------------------------------------------------------------------------

//- ----------------------------------------------------------------------------------------------------------------------
//- ----------------------------------------------------------------------------------------------------------------------
//                                   FW  moID   serial                         ST  devInfo
// <- 1A 01 A4 00 01 02 05 63 19 63  15  00 6C  74 6C 75 31 30 30 31 32 33 35  10  11 01 00 
// FW   -> Firmware, sometimes given in xml files of hm config software
// moID -> Model ID, important for identification in hm config software
// ST   -> Subtype, identifier if device is a switch or a dimmer or a remote
// devInfo -> Device Info -> sometimes hm config files are refering on byte 23 for the amount of channels, other bytes not known
//                           23:0 0.4, means first four bit of byte 23 reflecting the amount of channels
//
//- settings of HM device for AS class -----------------------------------------------------------------------------------
const uint8_t devIdnt[] PROGMEM = {
    /* Firmware version 1 byte */  0x25,
    /* Model ID         2 byte */  0x00, 0xb8,
    /* Sub Type ID      1 byte */  0x00,
    /* Device Info      3 byte */  0x41, 0x01, 0x00, 
};

//- ----------------------------------------------------------------------------------------------------------------------
//- channel slice address definition -------------------------------------------------------------------------------------
const uint8_t cnlAddr[] PROGMEM = {
    0x02, 0x0a, 0x0b, 0x0c, 0x15, 0x18,
    0x12, 0x30, 0x31, 0x56, 0x57, 0x59,
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x26, 0x27, 0x28, 0x29, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa6, 0xa7, 0xa8, 0xa9,
};  // 72 byte

//- channel device list table --------------------------------------------------------------------------------------------
EE::s_cnlTbl cnlTbl[] = {
    // cnl, lst, sIdx, sLen, pAddr;
    {  0,  0, 0x00,  6,  0x000f, 0 },
    {  1,  1, 0x06,  6,  0x0015, 0 },
    {  1,  3, 0x0c, 60,  0x001b, 0 },
    {  2,  1, 0x06,  6,  0x0057, 0 },
    {  2,  3, 0x0c, 60,  0x005d, 0 },
    {  3,  1, 0x07,  5,  0x0099, 0 },
    {  3,  3, 0x0c, 60,  0x009e, 0 },
    {  4,  1, 0x07,  5,  0x00da, 0 },
    {  4,  3, 0x0c, 60,  0x00df, 0 },
    {  5,  1, 0x07,  5,  0x011b, 0 },
    {  5,  3, 0x0c, 60,  0x0120, 0 },
    {  6,  1, 0x07,  5,  0x015c, 0 },
    {  6,  3, 0x0c, 60,  0x0161, 0 },
};  // 78 byte

//- peer device list table -----------------------------------------------------------------------------------------------
EE::s_peerTbl peerTbl[] = {
    // cnl, pMax, pAddr;
    {  1,  1, 0x019d },
    {  2,  1, 0x01a1 },
    {  3,  1, 0x01a5 },
    {  4,  1, 0x01a9 },
    {  5,  1, 0x01ad },
    {  6,  1, 0x01b1 },
};  // 24 byte

//- handover to AskSin lib -----------------------------------------------------------------------------------------------
EE::s_devDef devDef = {
    6, 13, devIdnt, cnlAddr,
};  // 10 byte

//- module registrar -----------------------------------------------------------------------------------------------------
RG::s_modTable modTbl[6];



//- ----------------------------------------------------------------------------------------------------------------------
//- only if needed -------------------------------------------------------------------------------------------------------
//- ----------------------------------------------------------------------------------------------------------------------

struct s_lst0Cnl0 {
// 0x02, 0x0a, 0x0b, 0x0c, 0x15, 0x18, 
    uint8_t                           :7;       // 0x02, s:0, e:7 
    uint8_t INTERNAL_KEYS_VISIBLE     :1;       // 0x02, s:7, e:8 
    uint8_t Master_ID_A               :8;       // 0x0a, s:0, e:8 
    uint8_t Master_ID_B               :8;       // 0x0b, s:0, e:8 
    uint8_t Master_ID_C               :8;       // 0x0c, s:0, e:8 
    uint8_t CONF_BUTTON_TIME          :8;       // 0x15, s:0, e:8 
    uint8_t LOCAL_RESET_DISABLE       :1;       // 0x18, s:0, e:1 
    uint8_t                           :7;       // 0x18, s:1, l:8 
};  // 6 byte

struct s_lst1Cnl1 {
// 0x12, 0x30, 0x31, 0x56, 0x57, 0x59, 
    uint8_t LOAD_ERROR_CALIB          :8;       // 0x12, s:0, e:8 
    uint8_t TRANSMIT_TRY_MAX          :8;       // 0x30, s:0, e:8 
    uint8_t LOAD_APPEAR_BEHAVIOUR     :2;       // 0x31, s:0, e:2 
    uint8_t                           :6;       // 0x31, s:2, l:8 
    uint8_t POWERUP_ACTION            :1;       // 0x56, s:0, e:1 
    uint8_t                           :7;       // 0x56, s:1, l:8 
    uint8_t STATUSINFO_MINDELAY       :5;       // 0x57, s:0, e:5 
    uint8_t STATUSINFO_RANDOM         :3;       // 0x57, s:5, e:8 
    uint8_t LOGIC_COMBINATION         :5;       // 0x59, s:0, e:5 
    uint8_t                           :3;       // 0x59, s:5, l:8 
};  // 6 byte

struct s_lst3Cnl1 {
// 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x26, 0x27, 0x28, 0x29, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa6, 0xa7, 0xa8, 0xa9,
    uint8_t SHORT_CT_RAMPON           :4;       // 0x01, s:0, e:4 
    uint8_t SHORT_CT_RAMPOFF          :4;       // 0x01, s:4, e:8 
    uint8_t SHORT_CT_ONDELAY          :4;       // 0x02, s:0, e:4 
    uint8_t SHORT_CT_OFFDELAY         :4;       // 0x02, s:4, e:8 
    uint8_t SHORT_CT_ON               :4;       // 0x03, s:0, e:4 
    uint8_t SHORT_CT_OFF              :4;       // 0x03, s:4, e:8 
    uint8_t SHORT_COND_VALUE_LO       :8;       // 0x04, s:0, e:8 
    uint8_t SHORT_COND_VALUE_HI       :8;       // 0x05, s:0, e:8 
    uint8_t SHORT_ONDELAY_TIME        :8;       // 0x06, s:0, e:8 
    uint8_t SHORT_ON_TIME             :8;       // 0x07, s:0, e:8 
    uint8_t SHORT_OFFDELAY_TIME       :8;       // 0x08, s:0, e:8 
    uint8_t SHORT_OFF_TIME            :8;       // 0x09, s:0, e:8 
    uint8_t SHORT_ACTION_TYPE         :4;       // 0x0a, s:0, e:4 
    uint8_t                           :2;       // 0x0a, s:4, e:6 
    uint8_t SHORT_OFF_TIME_MODE       :1;       // 0x0a, s:6, e:7 
    uint8_t SHORT_ON_TIME_MODE        :1;       // 0x0a, s:7, e:8 
    uint8_t SHORT_JT_ON               :4;       // 0x0b, s:0, e:4 
    uint8_t SHORT_JT_OFF              :4;       // 0x0b, s:4, e:8 
    uint8_t SHORT_JT_ONDELAY          :4;       // 0x0c, s:0, e:4 
    uint8_t SHORT_JT_OFFDELAY         :4;       // 0x0c, s:4, e:8 
    uint8_t SHORT_JT_RAMPON           :4;       // 0x0d, s:0, e:4 
    uint8_t SHORT_JT_RAMPOFF          :4;       // 0x0d, s:4, e:8 
    uint8_t                           :5;       // 0x0e, s:0, e:5 
    uint8_t SHORT_OFFDELAY_BLINK      :1;       // 0x0e, s:5, e:6 
    uint8_t SHORT_ON_LEVEL_PRIO       :1;       // 0x0e, s:6, e:7 
    uint8_t SHORT_ONDELAY_MODE        :1;       // 0x0e, s:7, e:8 
    uint8_t SHORT_OFF_LEVEL           :8;       // 0x0f, s:0, e:8 
    uint8_t SHORT_ON_MIN_LEVEL        :8;       // 0x10, s:0, e:8 
    uint8_t SHORT_ON_LEVEL            :8;       // 0x11, s:0, e:8 
    uint8_t SHORT_RAMP_START_STEP     :8;       // 0x12, s:0, e:8 
    uint8_t SHORT_RAMPON_TIME         :8;       // 0x13, s:0, e:8 
    uint8_t SHORT_RAMPOFF_TIME        :8;       // 0x14, s:0, e:8 
    uint8_t SHORT_DIM_MIN_LEVEL       :8;       // 0x15, s:0, e:8 
    uint8_t SHORT_DIM_MAX_LEVEL       :8;       // 0x16, s:0, e:8 
    uint8_t SHORT_DIM_STEP            :8;       // 0x17, s:0, e:8 
    uint8_t SHORT_OFFDELAY_STEP       :8;       // 0x18, s:0, e:8 
    uint8_t SHORT_OFFDELAY_NEWTIME    :8;       // 0x19, s:0, e:8 
    uint8_t SHORT_OFFDELAY_OLDTIME    :8;       // 0x1a, s:0, e:8 
    uint8_t SHORT_ELSE_ACTION_TYPE    :4;       // 0x26, s:0, e:4 
    uint8_t                           :2;       // 0x26, s:4, e:6 
    uint8_t SHORT_ELSE_OFF_TIME_MODE  :1;       // 0x26, s:6, e:7 
    uint8_t SHORT_ELSE_ON_TIME_MODE   :1;       // 0x26, s:7, e:8 
    uint8_t SHORT_ELSE_JT_ON          :4;       // 0x27, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFF         :4;       // 0x27, s:4, e:8 
    uint8_t SHORT_ELSE_JT_ONDELAY     :4;       // 0x28, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFFDELAY    :4;       // 0x28, s:4, e:8 
    uint8_t SHORT_ELSE_JT_RAMPON      :4;       // 0x29, s:0, e:4 
    uint8_t SHORT_ELSE_JT_RAMPOFF     :4;       // 0x29, s:4, e:8 
    uint8_t LONG_CT_RAMPON            :4;       // 0x81, s:0, e:4 
    uint8_t LONG_CT_RAMPOFF           :4;       // 0x81, s:4, e:8 
    uint8_t LONG_CT_ONDELAY           :4;       // 0x82, s:0, e:4 
    uint8_t LONG_CT_OFFDELAY          :4;       // 0x82, s:4, e:8 
    uint8_t LONG_CT_ON                :4;       // 0x83, s:0, e:4 
    uint8_t LONG_CT_OFF               :4;       // 0x83, s:4, e:8 
    uint8_t LONG_COND_VALUE_LO        :8;       // 0x84, s:0, e:8 
    uint8_t LONG_COND_VALUE_HI        :8;       // 0x85, s:0, e:8 
    uint8_t LONG_ONDELAY_TIME         :8;       // 0x86, s:0, e:8 
    uint8_t LONG_ON_TIME              :8;       // 0x87, s:0, e:8 
    uint8_t LONG_OFFDELAY_TIME        :8;       // 0x88, s:0, e:8 
    uint8_t LONG_OFF_TIME             :8;       // 0x89, s:0, e:8 
    uint8_t LONG_ACTION_TYPE          :4;       // 0x8a, s:0, e:4 
    uint8_t                           :1;       // 0x8a, s:4, e:5 
    uint8_t LONG_MULTIEXECUTE         :1;       // 0x8a, s:5, e:6 
    uint8_t LONG_OFF_TIME_MODE        :1;       // 0x8a, s:6, e:7 
    uint8_t LONG_ON_TIME_MODE         :1;       // 0x8a, s:7, e:8 
    uint8_t LONG_JT_ON                :4;       // 0x8b, s:0, e:4 
    uint8_t LONG_JT_OFF               :4;       // 0x8b, s:4, e:8 
    uint8_t LONG_JT_ONDELAY           :4;       // 0x8c, s:0, e:4 
    uint8_t LONG_JT_OFFDELAY          :4;       // 0x8c, s:4, e:8 
    uint8_t LONG_JT_RAMPON            :4;       // 0x8d, s:0, e:4 
    uint8_t LONG_JT_RAMPOFF           :4;       // 0x8d, s:4, e:8 
    uint8_t                           :5;       // 0x8e, s:0, e:5 
    uint8_t LONG_OFFDELAY_BLINK       :1;       // 0x8e, s:5, e:6 
    uint8_t LONG_ON_LEVEL_PRIO        :1;       // 0x8e, s:6, e:7 
    uint8_t LONG_ONDELAY_MODE         :1;       // 0x8e, s:7, e:8 
    uint8_t LONG_OFF_LEVEL            :8;       // 0x8f, s:0, e:8 
    uint8_t LONG_ON_MIN_LEVEL         :8;       // 0x90, s:0, e:8 
    uint8_t LONG_ON_LEVEL             :8;       // 0x91, s:0, e:8 
    uint8_t LONG_RAMP_START_STEP      :8;       // 0x92, s:0, e:8 
    uint8_t LONG_RAMPON_TIME          :8;       // 0x93, s:0, e:8 
    uint8_t LONG_RAMPOFF_TIME         :8;       // 0x94, s:0, e:8 
    uint8_t LONG_DIM_MIN_LEVEL        :8;       // 0x95, s:0, e:8 
    uint8_t LONG_DIM_MAX_LEVEL        :8;       // 0x96, s:0, e:8 
    uint8_t LONG_DIM_STEP             :8;       // 0x97, s:0, e:8 
    uint8_t LONG_OFFDELAY_STEP        :8;       // 0x98, s:0, e:8 
    uint8_t LONG_OFFDELAY_NEWTIME     :8;       // 0x99, s:0, e:8 
    uint8_t LONG_OFFDELAY_OLDTIME     :8;       // 0x9a, s:0, e:8 
    uint8_t LONG_ELSE_ACTION_TYPE     :4;       // 0xa6, s:0, e:4 
    uint8_t                           :1;       // 0xa6, s:4, e:5 
    uint8_t LONG_ELSE_MULTIEXECUTE    :1;       // 0xa6, s:5, e:6 
    uint8_t LONG_ELSE_OFF_TIME_MODE   :1;       // 0xa6, s:6, e:7 
    uint8_t LONG_ELSE_ON_TIME_MODE    :1;       // 0xa6, s:7, e:8 
    uint8_t LONG_ELSE_JT_ON           :4;       // 0xa7, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFF          :4;       // 0xa7, s:4, e:8 
    uint8_t LONG_ELSE_JT_ONDELAY      :4;       // 0xa8, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFFDELAY     :4;       // 0xa8, s:4, e:8 
    uint8_t LONG_ELSE_JT_RAMPON       :4;       // 0xa9, s:0, e:4 
    uint8_t LONG_ELSE_JT_RAMPOFF      :4;       // 0xa9, s:4, e:8 
};  // 60 byte

struct s_lst1Cnl2 {
// 0x12, 0x30, 0x31, 0x56, 0x57, 0x59, 
    uint8_t LOAD_ERROR_CALIB          :8;       // 0x12, s:0, e:8 
    uint8_t TRANSMIT_TRY_MAX          :8;       // 0x30, s:0, e:8 
    uint8_t LOAD_APPEAR_BEHAVIOUR     :2;       // 0x31, s:0, e:2 
    uint8_t                           :6;       // 0x31, s:2, l:8 
    uint8_t POWERUP_ACTION            :1;       // 0x56, s:0, e:1 
    uint8_t                           :7;       // 0x56, s:1, l:8 
    uint8_t STATUSINFO_MINDELAY       :5;       // 0x57, s:0, e:5 
    uint8_t STATUSINFO_RANDOM         :3;       // 0x57, s:5, e:8 
    uint8_t LOGIC_COMBINATION         :5;       // 0x59, s:0, e:5 
    uint8_t                           :3;       // 0x59, s:5, l:8 
};  // 6 byte

struct s_lst3Cnl2 {
// 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x26, 0x27, 0x28, 0x29, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa6, 0xa7, 0xa8, 0xa9,
    uint8_t SHORT_CT_RAMPON           :4;       // 0x01, s:0, e:4 
    uint8_t SHORT_CT_RAMPOFF          :4;       // 0x01, s:4, e:8 
    uint8_t SHORT_CT_ONDELAY          :4;       // 0x02, s:0, e:4 
    uint8_t SHORT_CT_OFFDELAY         :4;       // 0x02, s:4, e:8 
    uint8_t SHORT_CT_ON               :4;       // 0x03, s:0, e:4 
    uint8_t SHORT_CT_OFF              :4;       // 0x03, s:4, e:8 
    uint8_t SHORT_COND_VALUE_LO       :8;       // 0x04, s:0, e:8 
    uint8_t SHORT_COND_VALUE_HI       :8;       // 0x05, s:0, e:8 
    uint8_t SHORT_ONDELAY_TIME        :8;       // 0x06, s:0, e:8 
    uint8_t SHORT_ON_TIME             :8;       // 0x07, s:0, e:8 
    uint8_t SHORT_OFFDELAY_TIME       :8;       // 0x08, s:0, e:8 
    uint8_t SHORT_OFF_TIME            :8;       // 0x09, s:0, e:8 
    uint8_t SHORT_ACTION_TYPE         :4;       // 0x0a, s:0, e:4 
    uint8_t                           :2;       // 0x0a, s:4, e:6 
    uint8_t SHORT_OFF_TIME_MODE       :1;       // 0x0a, s:6, e:7 
    uint8_t SHORT_ON_TIME_MODE        :1;       // 0x0a, s:7, e:8 
    uint8_t SHORT_JT_ON               :4;       // 0x0b, s:0, e:4 
    uint8_t SHORT_JT_OFF              :4;       // 0x0b, s:4, e:8 
    uint8_t SHORT_JT_ONDELAY          :4;       // 0x0c, s:0, e:4 
    uint8_t SHORT_JT_OFFDELAY         :4;       // 0x0c, s:4, e:8 
    uint8_t SHORT_JT_RAMPON           :4;       // 0x0d, s:0, e:4 
    uint8_t SHORT_JT_RAMPOFF          :4;       // 0x0d, s:4, e:8 
    uint8_t                           :5;       // 0x0e, s:0, e:5 
    uint8_t SHORT_OFFDELAY_BLINK      :1;       // 0x0e, s:5, e:6 
    uint8_t SHORT_ON_LEVEL_PRIO       :1;       // 0x0e, s:6, e:7 
    uint8_t SHORT_ONDELAY_MODE        :1;       // 0x0e, s:7, e:8 
    uint8_t SHORT_OFF_LEVEL           :8;       // 0x0f, s:0, e:8 
    uint8_t SHORT_ON_MIN_LEVEL        :8;       // 0x10, s:0, e:8 
    uint8_t SHORT_ON_LEVEL            :8;       // 0x11, s:0, e:8 
    uint8_t SHORT_RAMP_START_STEP     :8;       // 0x12, s:0, e:8 
    uint8_t SHORT_RAMPON_TIME         :8;       // 0x13, s:0, e:8 
    uint8_t SHORT_RAMPOFF_TIME        :8;       // 0x14, s:0, e:8 
    uint8_t SHORT_DIM_MIN_LEVEL       :8;       // 0x15, s:0, e:8 
    uint8_t SHORT_DIM_MAX_LEVEL       :8;       // 0x16, s:0, e:8 
    uint8_t SHORT_DIM_STEP            :8;       // 0x17, s:0, e:8 
    uint8_t SHORT_OFFDELAY_STEP       :8;       // 0x18, s:0, e:8 
    uint8_t SHORT_OFFDELAY_NEWTIME    :8;       // 0x19, s:0, e:8 
    uint8_t SHORT_OFFDELAY_OLDTIME    :8;       // 0x1a, s:0, e:8 
    uint8_t SHORT_ELSE_ACTION_TYPE    :4;       // 0x26, s:0, e:4 
    uint8_t                           :2;       // 0x26, s:4, e:6 
    uint8_t SHORT_ELSE_OFF_TIME_MODE  :1;       // 0x26, s:6, e:7 
    uint8_t SHORT_ELSE_ON_TIME_MODE   :1;       // 0x26, s:7, e:8 
    uint8_t SHORT_ELSE_JT_ON          :4;       // 0x27, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFF         :4;       // 0x27, s:4, e:8 
    uint8_t SHORT_ELSE_JT_ONDELAY     :4;       // 0x28, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFFDELAY    :4;       // 0x28, s:4, e:8 
    uint8_t SHORT_ELSE_JT_RAMPON      :4;       // 0x29, s:0, e:4 
    uint8_t SHORT_ELSE_JT_RAMPOFF     :4;       // 0x29, s:4, e:8 
    uint8_t LONG_CT_RAMPON            :4;       // 0x81, s:0, e:4 
    uint8_t LONG_CT_RAMPOFF           :4;       // 0x81, s:4, e:8 
    uint8_t LONG_CT_ONDELAY           :4;       // 0x82, s:0, e:4 
    uint8_t LONG_CT_OFFDELAY          :4;       // 0x82, s:4, e:8 
    uint8_t LONG_CT_ON                :4;       // 0x83, s:0, e:4 
    uint8_t LONG_CT_OFF               :4;       // 0x83, s:4, e:8 
    uint8_t LONG_COND_VALUE_LO        :8;       // 0x84, s:0, e:8 
    uint8_t LONG_COND_VALUE_HI        :8;       // 0x85, s:0, e:8 
    uint8_t LONG_ONDELAY_TIME         :8;       // 0x86, s:0, e:8 
    uint8_t LONG_ON_TIME              :8;       // 0x87, s:0, e:8 
    uint8_t LONG_OFFDELAY_TIME        :8;       // 0x88, s:0, e:8 
    uint8_t LONG_OFF_TIME             :8;       // 0x89, s:0, e:8 
    uint8_t LONG_ACTION_TYPE          :4;       // 0x8a, s:0, e:4 
    uint8_t                           :1;       // 0x8a, s:4, e:5 
    uint8_t LONG_MULTIEXECUTE         :1;       // 0x8a, s:5, e:6 
    uint8_t LONG_OFF_TIME_MODE        :1;       // 0x8a, s:6, e:7 
    uint8_t LONG_ON_TIME_MODE         :1;       // 0x8a, s:7, e:8 
    uint8_t LONG_JT_ON                :4;       // 0x8b, s:0, e:4 
    uint8_t LONG_JT_OFF               :4;       // 0x8b, s:4, e:8 
    uint8_t LONG_JT_ONDELAY           :4;       // 0x8c, s:0, e:4 
    uint8_t LONG_JT_OFFDELAY          :4;       // 0x8c, s:4, e:8 
    uint8_t LONG_JT_RAMPON            :4;       // 0x8d, s:0, e:4 
    uint8_t LONG_JT_RAMPOFF           :4;       // 0x8d, s:4, e:8 
    uint8_t                           :5;       // 0x8e, s:0, e:5 
    uint8_t LONG_OFFDELAY_BLINK       :1;       // 0x8e, s:5, e:6 
    uint8_t LONG_ON_LEVEL_PRIO        :1;       // 0x8e, s:6, e:7 
    uint8_t LONG_ONDELAY_MODE         :1;       // 0x8e, s:7, e:8 
    uint8_t LONG_OFF_LEVEL            :8;       // 0x8f, s:0, e:8 
    uint8_t LONG_ON_MIN_LEVEL         :8;       // 0x90, s:0, e:8 
    uint8_t LONG_ON_LEVEL             :8;       // 0x91, s:0, e:8 
    uint8_t LONG_RAMP_START_STEP      :8;       // 0x92, s:0, e:8 
    uint8_t LONG_RAMPON_TIME          :8;       // 0x93, s:0, e:8 
    uint8_t LONG_RAMPOFF_TIME         :8;       // 0x94, s:0, e:8 
    uint8_t LONG_DIM_MIN_LEVEL        :8;       // 0x95, s:0, e:8 
    uint8_t LONG_DIM_MAX_LEVEL        :8;       // 0x96, s:0, e:8 
    uint8_t LONG_DIM_STEP             :8;       // 0x97, s:0, e:8 
    uint8_t LONG_OFFDELAY_STEP        :8;       // 0x98, s:0, e:8 
    uint8_t LONG_OFFDELAY_NEWTIME     :8;       // 0x99, s:0, e:8 
    uint8_t LONG_OFFDELAY_OLDTIME     :8;       // 0x9a, s:0, e:8 
    uint8_t LONG_ELSE_ACTION_TYPE     :4;       // 0xa6, s:0, e:4 
    uint8_t                           :1;       // 0xa6, s:4, e:5 
    uint8_t LONG_ELSE_MULTIEXECUTE    :1;       // 0xa6, s:5, e:6 
    uint8_t LONG_ELSE_OFF_TIME_MODE   :1;       // 0xa6, s:6, e:7 
    uint8_t LONG_ELSE_ON_TIME_MODE    :1;       // 0xa6, s:7, e:8 
    uint8_t LONG_ELSE_JT_ON           :4;       // 0xa7, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFF          :4;       // 0xa7, s:4, e:8 
    uint8_t LONG_ELSE_JT_ONDELAY      :4;       // 0xa8, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFFDELAY     :4;       // 0xa8, s:4, e:8 
    uint8_t LONG_ELSE_JT_RAMPON       :4;       // 0xa9, s:0, e:4 
    uint8_t LONG_ELSE_JT_RAMPOFF      :4;       // 0xa9, s:4, e:8 
};  // 60 byte

struct s_lst1Cnl3 {
// 0x30, 0x31, 0x56, 0x57, 0x59, 
    uint8_t TRANSMIT_TRY_MAX          :8;       // 0x30, s:0, e:8 
    uint8_t LOAD_APPEAR_BEHAVIOUR     :2;       // 0x31, s:0, e:2 
    uint8_t                           :6;       // 0x31, s:2, l:8 
    uint8_t POWERUP_ACTION            :1;       // 0x56, s:0, e:1 
    uint8_t                           :7;       // 0x56, s:1, l:8 
    uint8_t STATUSINFO_MINDELAY       :5;       // 0x57, s:0, e:5 
    uint8_t STATUSINFO_RANDOM         :3;       // 0x57, s:5, e:8 
    uint8_t LOGIC_COMBINATION         :5;       // 0x59, s:0, e:5 
    uint8_t                           :3;       // 0x59, s:5, l:8 
};  // 5 byte

struct s_lst3Cnl3 {
// 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x26, 0x27, 0x28, 0x29, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa6, 0xa7, 0xa8, 0xa9,
    uint8_t SHORT_CT_RAMPON           :4;       // 0x01, s:0, e:4 
    uint8_t SHORT_CT_RAMPOFF          :4;       // 0x01, s:4, e:8 
    uint8_t SHORT_CT_ONDELAY          :4;       // 0x02, s:0, e:4 
    uint8_t SHORT_CT_OFFDELAY         :4;       // 0x02, s:4, e:8 
    uint8_t SHORT_CT_ON               :4;       // 0x03, s:0, e:4 
    uint8_t SHORT_CT_OFF              :4;       // 0x03, s:4, e:8 
    uint8_t SHORT_COND_VALUE_LO       :8;       // 0x04, s:0, e:8 
    uint8_t SHORT_COND_VALUE_HI       :8;       // 0x05, s:0, e:8 
    uint8_t SHORT_ONDELAY_TIME        :8;       // 0x06, s:0, e:8 
    uint8_t SHORT_ON_TIME             :8;       // 0x07, s:0, e:8 
    uint8_t SHORT_OFFDELAY_TIME       :8;       // 0x08, s:0, e:8 
    uint8_t SHORT_OFF_TIME            :8;       // 0x09, s:0, e:8 
    uint8_t SHORT_ACTION_TYPE         :4;       // 0x0a, s:0, e:4 
    uint8_t                           :2;       // 0x0a, s:4, e:6 
    uint8_t SHORT_OFF_TIME_MODE       :1;       // 0x0a, s:6, e:7 
    uint8_t SHORT_ON_TIME_MODE        :1;       // 0x0a, s:7, e:8 
    uint8_t SHORT_JT_ON               :4;       // 0x0b, s:0, e:4 
    uint8_t SHORT_JT_OFF              :4;       // 0x0b, s:4, e:8 
    uint8_t SHORT_JT_ONDELAY          :4;       // 0x0c, s:0, e:4 
    uint8_t SHORT_JT_OFFDELAY         :4;       // 0x0c, s:4, e:8 
    uint8_t SHORT_JT_RAMPON           :4;       // 0x0d, s:0, e:4 
    uint8_t SHORT_JT_RAMPOFF          :4;       // 0x0d, s:4, e:8 
    uint8_t                           :5;       // 0x0e, s:0, e:5 
    uint8_t SHORT_OFFDELAY_BLINK      :1;       // 0x0e, s:5, e:6 
    uint8_t SHORT_ON_LEVEL_PRIO       :1;       // 0x0e, s:6, e:7 
    uint8_t SHORT_ONDELAY_MODE        :1;       // 0x0e, s:7, e:8 
    uint8_t SHORT_OFF_LEVEL           :8;       // 0x0f, s:0, e:8 
    uint8_t SHORT_ON_MIN_LEVEL        :8;       // 0x10, s:0, e:8 
    uint8_t SHORT_ON_LEVEL            :8;       // 0x11, s:0, e:8 
    uint8_t SHORT_RAMP_START_STEP     :8;       // 0x12, s:0, e:8 
    uint8_t SHORT_RAMPON_TIME         :8;       // 0x13, s:0, e:8 
    uint8_t SHORT_RAMPOFF_TIME        :8;       // 0x14, s:0, e:8 
    uint8_t SHORT_DIM_MIN_LEVEL       :8;       // 0x15, s:0, e:8 
    uint8_t SHORT_DIM_MAX_LEVEL       :8;       // 0x16, s:0, e:8 
    uint8_t SHORT_DIM_STEP            :8;       // 0x17, s:0, e:8 
    uint8_t SHORT_OFFDELAY_STEP       :8;       // 0x18, s:0, e:8 
    uint8_t SHORT_OFFDELAY_NEWTIME    :8;       // 0x19, s:0, e:8 
    uint8_t SHORT_OFFDELAY_OLDTIME    :8;       // 0x1a, s:0, e:8 
    uint8_t SHORT_ELSE_ACTION_TYPE    :4;       // 0x26, s:0, e:4 
    uint8_t                           :2;       // 0x26, s:4, e:6 
    uint8_t SHORT_ELSE_OFF_TIME_MODE  :1;       // 0x26, s:6, e:7 
    uint8_t SHORT_ELSE_ON_TIME_MODE   :1;       // 0x26, s:7, e:8 
    uint8_t SHORT_ELSE_JT_ON          :4;       // 0x27, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFF         :4;       // 0x27, s:4, e:8 
    uint8_t SHORT_ELSE_JT_ONDELAY     :4;       // 0x28, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFFDELAY    :4;       // 0x28, s:4, e:8 
    uint8_t SHORT_ELSE_JT_RAMPON      :4;       // 0x29, s:0, e:4 
    uint8_t SHORT_ELSE_JT_RAMPOFF     :4;       // 0x29, s:4, e:8 
    uint8_t LONG_CT_RAMPON            :4;       // 0x81, s:0, e:4 
    uint8_t LONG_CT_RAMPOFF           :4;       // 0x81, s:4, e:8 
    uint8_t LONG_CT_ONDELAY           :4;       // 0x82, s:0, e:4 
    uint8_t LONG_CT_OFFDELAY          :4;       // 0x82, s:4, e:8 
    uint8_t LONG_CT_ON                :4;       // 0x83, s:0, e:4 
    uint8_t LONG_CT_OFF               :4;       // 0x83, s:4, e:8 
    uint8_t LONG_COND_VALUE_LO        :8;       // 0x84, s:0, e:8 
    uint8_t LONG_COND_VALUE_HI        :8;       // 0x85, s:0, e:8 
    uint8_t LONG_ONDELAY_TIME         :8;       // 0x86, s:0, e:8 
    uint8_t LONG_ON_TIME              :8;       // 0x87, s:0, e:8 
    uint8_t LONG_OFFDELAY_TIME        :8;       // 0x88, s:0, e:8 
    uint8_t LONG_OFF_TIME             :8;       // 0x89, s:0, e:8 
    uint8_t LONG_ACTION_TYPE          :4;       // 0x8a, s:0, e:4 
    uint8_t                           :1;       // 0x8a, s:4, e:5 
    uint8_t LONG_MULTIEXECUTE         :1;       // 0x8a, s:5, e:6 
    uint8_t LONG_OFF_TIME_MODE        :1;       // 0x8a, s:6, e:7 
    uint8_t LONG_ON_TIME_MODE         :1;       // 0x8a, s:7, e:8 
    uint8_t LONG_JT_ON                :4;       // 0x8b, s:0, e:4 
    uint8_t LONG_JT_OFF               :4;       // 0x8b, s:4, e:8 
    uint8_t LONG_JT_ONDELAY           :4;       // 0x8c, s:0, e:4 
    uint8_t LONG_JT_OFFDELAY          :4;       // 0x8c, s:4, e:8 
    uint8_t LONG_JT_RAMPON            :4;       // 0x8d, s:0, e:4 
    uint8_t LONG_JT_RAMPOFF           :4;       // 0x8d, s:4, e:8 
    uint8_t                           :5;       // 0x8e, s:0, e:5 
    uint8_t LONG_OFFDELAY_BLINK       :1;       // 0x8e, s:5, e:6 
    uint8_t LONG_ON_LEVEL_PRIO        :1;       // 0x8e, s:6, e:7 
    uint8_t LONG_ONDELAY_MODE         :1;       // 0x8e, s:7, e:8 
    uint8_t LONG_OFF_LEVEL            :8;       // 0x8f, s:0, e:8 
    uint8_t LONG_ON_MIN_LEVEL         :8;       // 0x90, s:0, e:8 
    uint8_t LONG_ON_LEVEL             :8;       // 0x91, s:0, e:8 
    uint8_t LONG_RAMP_START_STEP      :8;       // 0x92, s:0, e:8 
    uint8_t LONG_RAMPON_TIME          :8;       // 0x93, s:0, e:8 
    uint8_t LONG_RAMPOFF_TIME         :8;       // 0x94, s:0, e:8 
    uint8_t LONG_DIM_MIN_LEVEL        :8;       // 0x95, s:0, e:8 
    uint8_t LONG_DIM_MAX_LEVEL        :8;       // 0x96, s:0, e:8 
    uint8_t LONG_DIM_STEP             :8;       // 0x97, s:0, e:8 
    uint8_t LONG_OFFDELAY_STEP        :8;       // 0x98, s:0, e:8 
    uint8_t LONG_OFFDELAY_NEWTIME     :8;       // 0x99, s:0, e:8 
    uint8_t LONG_OFFDELAY_OLDTIME     :8;       // 0x9a, s:0, e:8 
    uint8_t LONG_ELSE_ACTION_TYPE     :4;       // 0xa6, s:0, e:4 
    uint8_t                           :1;       // 0xa6, s:4, e:5 
    uint8_t LONG_ELSE_MULTIEXECUTE    :1;       // 0xa6, s:5, e:6 
    uint8_t LONG_ELSE_OFF_TIME_MODE   :1;       // 0xa6, s:6, e:7 
    uint8_t LONG_ELSE_ON_TIME_MODE    :1;       // 0xa6, s:7, e:8 
    uint8_t LONG_ELSE_JT_ON           :4;       // 0xa7, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFF          :4;       // 0xa7, s:4, e:8 
    uint8_t LONG_ELSE_JT_ONDELAY      :4;       // 0xa8, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFFDELAY     :4;       // 0xa8, s:4, e:8 
    uint8_t LONG_ELSE_JT_RAMPON       :4;       // 0xa9, s:0, e:4 
    uint8_t LONG_ELSE_JT_RAMPOFF      :4;       // 0xa9, s:4, e:8 
};  // 60 byte

struct s_lst1Cnl4 {
// 0x30, 0x31, 0x56, 0x57, 0x59, 
    uint8_t TRANSMIT_TRY_MAX          :8;       // 0x30, s:0, e:8 
    uint8_t LOAD_APPEAR_BEHAVIOUR     :2;       // 0x31, s:0, e:2 
    uint8_t                           :6;       // 0x31, s:2, l:8 
    uint8_t POWERUP_ACTION            :1;       // 0x56, s:0, e:1 
    uint8_t                           :7;       // 0x56, s:1, l:8 
    uint8_t STATUSINFO_MINDELAY       :5;       // 0x57, s:0, e:5 
    uint8_t STATUSINFO_RANDOM         :3;       // 0x57, s:5, e:8 
    uint8_t LOGIC_COMBINATION         :5;       // 0x59, s:0, e:5 
    uint8_t                           :3;       // 0x59, s:5, l:8 
};  // 5 byte

struct s_lst3Cnl4 {
// 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x26, 0x27, 0x28, 0x29, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa6, 0xa7, 0xa8, 0xa9,
    uint8_t SHORT_CT_RAMPON           :4;       // 0x01, s:0, e:4 
    uint8_t SHORT_CT_RAMPOFF          :4;       // 0x01, s:4, e:8 
    uint8_t SHORT_CT_ONDELAY          :4;       // 0x02, s:0, e:4 
    uint8_t SHORT_CT_OFFDELAY         :4;       // 0x02, s:4, e:8 
    uint8_t SHORT_CT_ON               :4;       // 0x03, s:0, e:4 
    uint8_t SHORT_CT_OFF              :4;       // 0x03, s:4, e:8 
    uint8_t SHORT_COND_VALUE_LO       :8;       // 0x04, s:0, e:8 
    uint8_t SHORT_COND_VALUE_HI       :8;       // 0x05, s:0, e:8 
    uint8_t SHORT_ONDELAY_TIME        :8;       // 0x06, s:0, e:8 
    uint8_t SHORT_ON_TIME             :8;       // 0x07, s:0, e:8 
    uint8_t SHORT_OFFDELAY_TIME       :8;       // 0x08, s:0, e:8 
    uint8_t SHORT_OFF_TIME            :8;       // 0x09, s:0, e:8 
    uint8_t SHORT_ACTION_TYPE         :4;       // 0x0a, s:0, e:4 
    uint8_t                           :2;       // 0x0a, s:4, e:6 
    uint8_t SHORT_OFF_TIME_MODE       :1;       // 0x0a, s:6, e:7 
    uint8_t SHORT_ON_TIME_MODE        :1;       // 0x0a, s:7, e:8 
    uint8_t SHORT_JT_ON               :4;       // 0x0b, s:0, e:4 
    uint8_t SHORT_JT_OFF              :4;       // 0x0b, s:4, e:8 
    uint8_t SHORT_JT_ONDELAY          :4;       // 0x0c, s:0, e:4 
    uint8_t SHORT_JT_OFFDELAY         :4;       // 0x0c, s:4, e:8 
    uint8_t SHORT_JT_RAMPON           :4;       // 0x0d, s:0, e:4 
    uint8_t SHORT_JT_RAMPOFF          :4;       // 0x0d, s:4, e:8 
    uint8_t                           :5;       // 0x0e, s:0, e:5 
    uint8_t SHORT_OFFDELAY_BLINK      :1;       // 0x0e, s:5, e:6 
    uint8_t SHORT_ON_LEVEL_PRIO       :1;       // 0x0e, s:6, e:7 
    uint8_t SHORT_ONDELAY_MODE        :1;       // 0x0e, s:7, e:8 
    uint8_t SHORT_OFF_LEVEL           :8;       // 0x0f, s:0, e:8 
    uint8_t SHORT_ON_MIN_LEVEL        :8;       // 0x10, s:0, e:8 
    uint8_t SHORT_ON_LEVEL            :8;       // 0x11, s:0, e:8 
    uint8_t SHORT_RAMP_START_STEP     :8;       // 0x12, s:0, e:8 
    uint8_t SHORT_RAMPON_TIME         :8;       // 0x13, s:0, e:8 
    uint8_t SHORT_RAMPOFF_TIME        :8;       // 0x14, s:0, e:8 
    uint8_t SHORT_DIM_MIN_LEVEL       :8;       // 0x15, s:0, e:8 
    uint8_t SHORT_DIM_MAX_LEVEL       :8;       // 0x16, s:0, e:8 
    uint8_t SHORT_DIM_STEP            :8;       // 0x17, s:0, e:8 
    uint8_t SHORT_OFFDELAY_STEP       :8;       // 0x18, s:0, e:8 
    uint8_t SHORT_OFFDELAY_NEWTIME    :8;       // 0x19, s:0, e:8 
    uint8_t SHORT_OFFDELAY_OLDTIME    :8;       // 0x1a, s:0, e:8 
    uint8_t SHORT_ELSE_ACTION_TYPE    :4;       // 0x26, s:0, e:4 
    uint8_t                           :2;       // 0x26, s:4, e:6 
    uint8_t SHORT_ELSE_OFF_TIME_MODE  :1;       // 0x26, s:6, e:7 
    uint8_t SHORT_ELSE_ON_TIME_MODE   :1;       // 0x26, s:7, e:8 
    uint8_t SHORT_ELSE_JT_ON          :4;       // 0x27, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFF         :4;       // 0x27, s:4, e:8 
    uint8_t SHORT_ELSE_JT_ONDELAY     :4;       // 0x28, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFFDELAY    :4;       // 0x28, s:4, e:8 
    uint8_t SHORT_ELSE_JT_RAMPON      :4;       // 0x29, s:0, e:4 
    uint8_t SHORT_ELSE_JT_RAMPOFF     :4;       // 0x29, s:4, e:8 
    uint8_t LONG_CT_RAMPON            :4;       // 0x81, s:0, e:4 
    uint8_t LONG_CT_RAMPOFF           :4;       // 0x81, s:4, e:8 
    uint8_t LONG_CT_ONDELAY           :4;       // 0x82, s:0, e:4 
    uint8_t LONG_CT_OFFDELAY          :4;       // 0x82, s:4, e:8 
    uint8_t LONG_CT_ON                :4;       // 0x83, s:0, e:4 
    uint8_t LONG_CT_OFF               :4;       // 0x83, s:4, e:8 
    uint8_t LONG_COND_VALUE_LO        :8;       // 0x84, s:0, e:8 
    uint8_t LONG_COND_VALUE_HI        :8;       // 0x85, s:0, e:8 
    uint8_t LONG_ONDELAY_TIME         :8;       // 0x86, s:0, e:8 
    uint8_t LONG_ON_TIME              :8;       // 0x87, s:0, e:8 
    uint8_t LONG_OFFDELAY_TIME        :8;       // 0x88, s:0, e:8 
    uint8_t LONG_OFF_TIME             :8;       // 0x89, s:0, e:8 
    uint8_t LONG_ACTION_TYPE          :4;       // 0x8a, s:0, e:4 
    uint8_t                           :1;       // 0x8a, s:4, e:5 
    uint8_t LONG_MULTIEXECUTE         :1;       // 0x8a, s:5, e:6 
    uint8_t LONG_OFF_TIME_MODE        :1;       // 0x8a, s:6, e:7 
    uint8_t LONG_ON_TIME_MODE         :1;       // 0x8a, s:7, e:8 
    uint8_t LONG_JT_ON                :4;       // 0x8b, s:0, e:4 
    uint8_t LONG_JT_OFF               :4;       // 0x8b, s:4, e:8 
    uint8_t LONG_JT_ONDELAY           :4;       // 0x8c, s:0, e:4 
    uint8_t LONG_JT_OFFDELAY          :4;       // 0x8c, s:4, e:8 
    uint8_t LONG_JT_RAMPON            :4;       // 0x8d, s:0, e:4 
    uint8_t LONG_JT_RAMPOFF           :4;       // 0x8d, s:4, e:8 
    uint8_t                           :5;       // 0x8e, s:0, e:5 
    uint8_t LONG_OFFDELAY_BLINK       :1;       // 0x8e, s:5, e:6 
    uint8_t LONG_ON_LEVEL_PRIO        :1;       // 0x8e, s:6, e:7 
    uint8_t LONG_ONDELAY_MODE         :1;       // 0x8e, s:7, e:8 
    uint8_t LONG_OFF_LEVEL            :8;       // 0x8f, s:0, e:8 
    uint8_t LONG_ON_MIN_LEVEL         :8;       // 0x90, s:0, e:8 
    uint8_t LONG_ON_LEVEL             :8;       // 0x91, s:0, e:8 
    uint8_t LONG_RAMP_START_STEP      :8;       // 0x92, s:0, e:8 
    uint8_t LONG_RAMPON_TIME          :8;       // 0x93, s:0, e:8 
    uint8_t LONG_RAMPOFF_TIME         :8;       // 0x94, s:0, e:8 
    uint8_t LONG_DIM_MIN_LEVEL        :8;       // 0x95, s:0, e:8 
    uint8_t LONG_DIM_MAX_LEVEL        :8;       // 0x96, s:0, e:8 
    uint8_t LONG_DIM_STEP             :8;       // 0x97, s:0, e:8 
    uint8_t LONG_OFFDELAY_STEP        :8;       // 0x98, s:0, e:8 
    uint8_t LONG_OFFDELAY_NEWTIME     :8;       // 0x99, s:0, e:8 
    uint8_t LONG_OFFDELAY_OLDTIME     :8;       // 0x9a, s:0, e:8 
    uint8_t LONG_ELSE_ACTION_TYPE     :4;       // 0xa6, s:0, e:4 
    uint8_t                           :1;       // 0xa6, s:4, e:5 
    uint8_t LONG_ELSE_MULTIEXECUTE    :1;       // 0xa6, s:5, e:6 
    uint8_t LONG_ELSE_OFF_TIME_MODE   :1;       // 0xa6, s:6, e:7 
    uint8_t LONG_ELSE_ON_TIME_MODE    :1;       // 0xa6, s:7, e:8 
    uint8_t LONG_ELSE_JT_ON           :4;       // 0xa7, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFF          :4;       // 0xa7, s:4, e:8 
    uint8_t LONG_ELSE_JT_ONDELAY      :4;       // 0xa8, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFFDELAY     :4;       // 0xa8, s:4, e:8 
    uint8_t LONG_ELSE_JT_RAMPON       :4;       // 0xa9, s:0, e:4 
    uint8_t LONG_ELSE_JT_RAMPOFF      :4;       // 0xa9, s:4, e:8 
};  // 60 byte

struct s_lst1Cnl5 {
// 0x30, 0x31, 0x56, 0x57, 0x59, 
    uint8_t TRANSMIT_TRY_MAX          :8;       // 0x30, s:0, e:8 
    uint8_t LOAD_APPEAR_BEHAVIOUR     :2;       // 0x31, s:0, e:2 
    uint8_t                           :6;       // 0x31, s:2, l:8 
    uint8_t POWERUP_ACTION            :1;       // 0x56, s:0, e:1 
    uint8_t                           :7;       // 0x56, s:1, l:8 
    uint8_t STATUSINFO_MINDELAY       :5;       // 0x57, s:0, e:5 
    uint8_t STATUSINFO_RANDOM         :3;       // 0x57, s:5, e:8 
    uint8_t LOGIC_COMBINATION         :5;       // 0x59, s:0, e:5 
    uint8_t                           :3;       // 0x59, s:5, l:8 
};  // 5 byte

struct s_lst3Cnl5 {
// 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x26, 0x27, 0x28, 0x29, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa6, 0xa7, 0xa8, 0xa9,
    uint8_t SHORT_CT_RAMPON           :4;       // 0x01, s:0, e:4 
    uint8_t SHORT_CT_RAMPOFF          :4;       // 0x01, s:4, e:8 
    uint8_t SHORT_CT_ONDELAY          :4;       // 0x02, s:0, e:4 
    uint8_t SHORT_CT_OFFDELAY         :4;       // 0x02, s:4, e:8 
    uint8_t SHORT_CT_ON               :4;       // 0x03, s:0, e:4 
    uint8_t SHORT_CT_OFF              :4;       // 0x03, s:4, e:8 
    uint8_t SHORT_COND_VALUE_LO       :8;       // 0x04, s:0, e:8 
    uint8_t SHORT_COND_VALUE_HI       :8;       // 0x05, s:0, e:8 
    uint8_t SHORT_ONDELAY_TIME        :8;       // 0x06, s:0, e:8 
    uint8_t SHORT_ON_TIME             :8;       // 0x07, s:0, e:8 
    uint8_t SHORT_OFFDELAY_TIME       :8;       // 0x08, s:0, e:8 
    uint8_t SHORT_OFF_TIME            :8;       // 0x09, s:0, e:8 
    uint8_t SHORT_ACTION_TYPE         :4;       // 0x0a, s:0, e:4 
    uint8_t                           :2;       // 0x0a, s:4, e:6 
    uint8_t SHORT_OFF_TIME_MODE       :1;       // 0x0a, s:6, e:7 
    uint8_t SHORT_ON_TIME_MODE        :1;       // 0x0a, s:7, e:8 
    uint8_t SHORT_JT_ON               :4;       // 0x0b, s:0, e:4 
    uint8_t SHORT_JT_OFF              :4;       // 0x0b, s:4, e:8 
    uint8_t SHORT_JT_ONDELAY          :4;       // 0x0c, s:0, e:4 
    uint8_t SHORT_JT_OFFDELAY         :4;       // 0x0c, s:4, e:8 
    uint8_t SHORT_JT_RAMPON           :4;       // 0x0d, s:0, e:4 
    uint8_t SHORT_JT_RAMPOFF          :4;       // 0x0d, s:4, e:8 
    uint8_t                           :5;       // 0x0e, s:0, e:5 
    uint8_t SHORT_OFFDELAY_BLINK      :1;       // 0x0e, s:5, e:6 
    uint8_t SHORT_ON_LEVEL_PRIO       :1;       // 0x0e, s:6, e:7 
    uint8_t SHORT_ONDELAY_MODE        :1;       // 0x0e, s:7, e:8 
    uint8_t SHORT_OFF_LEVEL           :8;       // 0x0f, s:0, e:8 
    uint8_t SHORT_ON_MIN_LEVEL        :8;       // 0x10, s:0, e:8 
    uint8_t SHORT_ON_LEVEL            :8;       // 0x11, s:0, e:8 
    uint8_t SHORT_RAMP_START_STEP     :8;       // 0x12, s:0, e:8 
    uint8_t SHORT_RAMPON_TIME         :8;       // 0x13, s:0, e:8 
    uint8_t SHORT_RAMPOFF_TIME        :8;       // 0x14, s:0, e:8 
    uint8_t SHORT_DIM_MIN_LEVEL       :8;       // 0x15, s:0, e:8 
    uint8_t SHORT_DIM_MAX_LEVEL       :8;       // 0x16, s:0, e:8 
    uint8_t SHORT_DIM_STEP            :8;       // 0x17, s:0, e:8 
    uint8_t SHORT_OFFDELAY_STEP       :8;       // 0x18, s:0, e:8 
    uint8_t SHORT_OFFDELAY_NEWTIME    :8;       // 0x19, s:0, e:8 
    uint8_t SHORT_OFFDELAY_OLDTIME    :8;       // 0x1a, s:0, e:8 
    uint8_t SHORT_ELSE_ACTION_TYPE    :4;       // 0x26, s:0, e:4 
    uint8_t                           :2;       // 0x26, s:4, e:6 
    uint8_t SHORT_ELSE_OFF_TIME_MODE  :1;       // 0x26, s:6, e:7 
    uint8_t SHORT_ELSE_ON_TIME_MODE   :1;       // 0x26, s:7, e:8 
    uint8_t SHORT_ELSE_JT_ON          :4;       // 0x27, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFF         :4;       // 0x27, s:4, e:8 
    uint8_t SHORT_ELSE_JT_ONDELAY     :4;       // 0x28, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFFDELAY    :4;       // 0x28, s:4, e:8 
    uint8_t SHORT_ELSE_JT_RAMPON      :4;       // 0x29, s:0, e:4 
    uint8_t SHORT_ELSE_JT_RAMPOFF     :4;       // 0x29, s:4, e:8 
    uint8_t LONG_CT_RAMPON            :4;       // 0x81, s:0, e:4 
    uint8_t LONG_CT_RAMPOFF           :4;       // 0x81, s:4, e:8 
    uint8_t LONG_CT_ONDELAY           :4;       // 0x82, s:0, e:4 
    uint8_t LONG_CT_OFFDELAY          :4;       // 0x82, s:4, e:8 
    uint8_t LONG_CT_ON                :4;       // 0x83, s:0, e:4 
    uint8_t LONG_CT_OFF               :4;       // 0x83, s:4, e:8 
    uint8_t LONG_COND_VALUE_LO        :8;       // 0x84, s:0, e:8 
    uint8_t LONG_COND_VALUE_HI        :8;       // 0x85, s:0, e:8 
    uint8_t LONG_ONDELAY_TIME         :8;       // 0x86, s:0, e:8 
    uint8_t LONG_ON_TIME              :8;       // 0x87, s:0, e:8 
    uint8_t LONG_OFFDELAY_TIME        :8;       // 0x88, s:0, e:8 
    uint8_t LONG_OFF_TIME             :8;       // 0x89, s:0, e:8 
    uint8_t LONG_ACTION_TYPE          :4;       // 0x8a, s:0, e:4 
    uint8_t                           :1;       // 0x8a, s:4, e:5 
    uint8_t LONG_MULTIEXECUTE         :1;       // 0x8a, s:5, e:6 
    uint8_t LONG_OFF_TIME_MODE        :1;       // 0x8a, s:6, e:7 
    uint8_t LONG_ON_TIME_MODE         :1;       // 0x8a, s:7, e:8 
    uint8_t LONG_JT_ON                :4;       // 0x8b, s:0, e:4 
    uint8_t LONG_JT_OFF               :4;       // 0x8b, s:4, e:8 
    uint8_t LONG_JT_ONDELAY           :4;       // 0x8c, s:0, e:4 
    uint8_t LONG_JT_OFFDELAY          :4;       // 0x8c, s:4, e:8 
    uint8_t LONG_JT_RAMPON            :4;       // 0x8d, s:0, e:4 
    uint8_t LONG_JT_RAMPOFF           :4;       // 0x8d, s:4, e:8 
    uint8_t                           :5;       // 0x8e, s:0, e:5 
    uint8_t LONG_OFFDELAY_BLINK       :1;       // 0x8e, s:5, e:6 
    uint8_t LONG_ON_LEVEL_PRIO        :1;       // 0x8e, s:6, e:7 
    uint8_t LONG_ONDELAY_MODE         :1;       // 0x8e, s:7, e:8 
    uint8_t LONG_OFF_LEVEL            :8;       // 0x8f, s:0, e:8 
    uint8_t LONG_ON_MIN_LEVEL         :8;       // 0x90, s:0, e:8 
    uint8_t LONG_ON_LEVEL             :8;       // 0x91, s:0, e:8 
    uint8_t LONG_RAMP_START_STEP      :8;       // 0x92, s:0, e:8 
    uint8_t LONG_RAMPON_TIME          :8;       // 0x93, s:0, e:8 
    uint8_t LONG_RAMPOFF_TIME         :8;       // 0x94, s:0, e:8 
    uint8_t LONG_DIM_MIN_LEVEL        :8;       // 0x95, s:0, e:8 
    uint8_t LONG_DIM_MAX_LEVEL        :8;       // 0x96, s:0, e:8 
    uint8_t LONG_DIM_STEP             :8;       // 0x97, s:0, e:8 
    uint8_t LONG_OFFDELAY_STEP        :8;       // 0x98, s:0, e:8 
    uint8_t LONG_OFFDELAY_NEWTIME     :8;       // 0x99, s:0, e:8 
    uint8_t LONG_OFFDELAY_OLDTIME     :8;       // 0x9a, s:0, e:8 
    uint8_t LONG_ELSE_ACTION_TYPE     :4;       // 0xa6, s:0, e:4 
    uint8_t                           :1;       // 0xa6, s:4, e:5 
    uint8_t LONG_ELSE_MULTIEXECUTE    :1;       // 0xa6, s:5, e:6 
    uint8_t LONG_ELSE_OFF_TIME_MODE   :1;       // 0xa6, s:6, e:7 
    uint8_t LONG_ELSE_ON_TIME_MODE    :1;       // 0xa6, s:7, e:8 
    uint8_t LONG_ELSE_JT_ON           :4;       // 0xa7, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFF          :4;       // 0xa7, s:4, e:8 
    uint8_t LONG_ELSE_JT_ONDELAY      :4;       // 0xa8, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFFDELAY     :4;       // 0xa8, s:4, e:8 
    uint8_t LONG_ELSE_JT_RAMPON       :4;       // 0xa9, s:0, e:4 
    uint8_t LONG_ELSE_JT_RAMPOFF      :4;       // 0xa9, s:4, e:8 
};  // 60 byte

struct s_lst1Cnl6 {
// 0x30, 0x31, 0x56, 0x57, 0x59, 
    uint8_t TRANSMIT_TRY_MAX          :8;       // 0x30, s:0, e:8 
    uint8_t LOAD_APPEAR_BEHAVIOUR     :2;       // 0x31, s:0, e:2 
    uint8_t                           :6;       // 0x31, s:2, l:8 
    uint8_t POWERUP_ACTION            :1;       // 0x56, s:0, e:1 
    uint8_t                           :7;       // 0x56, s:1, l:8 
    uint8_t STATUSINFO_MINDELAY       :5;       // 0x57, s:0, e:5 
    uint8_t STATUSINFO_RANDOM         :3;       // 0x57, s:5, e:8 
    uint8_t LOGIC_COMBINATION         :5;       // 0x59, s:0, e:5 
    uint8_t                           :3;       // 0x59, s:5, l:8 
};  // 5 byte

struct s_lst3Cnl6 {
// 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x26, 0x27, 0x28, 0x29, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa6, 0xa7, 0xa8, 0xa9,
    uint8_t SHORT_CT_RAMPON           :4;       // 0x01, s:0, e:4 
    uint8_t SHORT_CT_RAMPOFF          :4;       // 0x01, s:4, e:8 
    uint8_t SHORT_CT_ONDELAY          :4;       // 0x02, s:0, e:4 
    uint8_t SHORT_CT_OFFDELAY         :4;       // 0x02, s:4, e:8 
    uint8_t SHORT_CT_ON               :4;       // 0x03, s:0, e:4 
    uint8_t SHORT_CT_OFF              :4;       // 0x03, s:4, e:8 
    uint8_t SHORT_COND_VALUE_LO       :8;       // 0x04, s:0, e:8 
    uint8_t SHORT_COND_VALUE_HI       :8;       // 0x05, s:0, e:8 
    uint8_t SHORT_ONDELAY_TIME        :8;       // 0x06, s:0, e:8 
    uint8_t SHORT_ON_TIME             :8;       // 0x07, s:0, e:8 
    uint8_t SHORT_OFFDELAY_TIME       :8;       // 0x08, s:0, e:8 
    uint8_t SHORT_OFF_TIME            :8;       // 0x09, s:0, e:8 
    uint8_t SHORT_ACTION_TYPE         :4;       // 0x0a, s:0, e:4 
    uint8_t                           :2;       // 0x0a, s:4, e:6 
    uint8_t SHORT_OFF_TIME_MODE       :1;       // 0x0a, s:6, e:7 
    uint8_t SHORT_ON_TIME_MODE        :1;       // 0x0a, s:7, e:8 
    uint8_t SHORT_JT_ON               :4;       // 0x0b, s:0, e:4 
    uint8_t SHORT_JT_OFF              :4;       // 0x0b, s:4, e:8 
    uint8_t SHORT_JT_ONDELAY          :4;       // 0x0c, s:0, e:4 
    uint8_t SHORT_JT_OFFDELAY         :4;       // 0x0c, s:4, e:8 
    uint8_t SHORT_JT_RAMPON           :4;       // 0x0d, s:0, e:4 
    uint8_t SHORT_JT_RAMPOFF          :4;       // 0x0d, s:4, e:8 
    uint8_t                           :5;       // 0x0e, s:0, e:5 
    uint8_t SHORT_OFFDELAY_BLINK      :1;       // 0x0e, s:5, e:6 
    uint8_t SHORT_ON_LEVEL_PRIO       :1;       // 0x0e, s:6, e:7 
    uint8_t SHORT_ONDELAY_MODE        :1;       // 0x0e, s:7, e:8 
    uint8_t SHORT_OFF_LEVEL           :8;       // 0x0f, s:0, e:8 
    uint8_t SHORT_ON_MIN_LEVEL        :8;       // 0x10, s:0, e:8 
    uint8_t SHORT_ON_LEVEL            :8;       // 0x11, s:0, e:8 
    uint8_t SHORT_RAMP_START_STEP     :8;       // 0x12, s:0, e:8 
    uint8_t SHORT_RAMPON_TIME         :8;       // 0x13, s:0, e:8 
    uint8_t SHORT_RAMPOFF_TIME        :8;       // 0x14, s:0, e:8 
    uint8_t SHORT_DIM_MIN_LEVEL       :8;       // 0x15, s:0, e:8 
    uint8_t SHORT_DIM_MAX_LEVEL       :8;       // 0x16, s:0, e:8 
    uint8_t SHORT_DIM_STEP            :8;       // 0x17, s:0, e:8 
    uint8_t SHORT_OFFDELAY_STEP       :8;       // 0x18, s:0, e:8 
    uint8_t SHORT_OFFDELAY_NEWTIME    :8;       // 0x19, s:0, e:8 
    uint8_t SHORT_OFFDELAY_OLDTIME    :8;       // 0x1a, s:0, e:8 
    uint8_t SHORT_ELSE_ACTION_TYPE    :4;       // 0x26, s:0, e:4 
    uint8_t                           :2;       // 0x26, s:4, e:6 
    uint8_t SHORT_ELSE_OFF_TIME_MODE  :1;       // 0x26, s:6, e:7 
    uint8_t SHORT_ELSE_ON_TIME_MODE   :1;       // 0x26, s:7, e:8 
    uint8_t SHORT_ELSE_JT_ON          :4;       // 0x27, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFF         :4;       // 0x27, s:4, e:8 
    uint8_t SHORT_ELSE_JT_ONDELAY     :4;       // 0x28, s:0, e:4 
    uint8_t SHORT_ELSE_JT_OFFDELAY    :4;       // 0x28, s:4, e:8 
    uint8_t SHORT_ELSE_JT_RAMPON      :4;       // 0x29, s:0, e:4 
    uint8_t SHORT_ELSE_JT_RAMPOFF     :4;       // 0x29, s:4, e:8 
    uint8_t LONG_CT_RAMPON            :4;       // 0x81, s:0, e:4 
    uint8_t LONG_CT_RAMPOFF           :4;       // 0x81, s:4, e:8 
    uint8_t LONG_CT_ONDELAY           :4;       // 0x82, s:0, e:4 
    uint8_t LONG_CT_OFFDELAY          :4;       // 0x82, s:4, e:8 
    uint8_t LONG_CT_ON                :4;       // 0x83, s:0, e:4 
    uint8_t LONG_CT_OFF               :4;       // 0x83, s:4, e:8 
    uint8_t LONG_COND_VALUE_LO        :8;       // 0x84, s:0, e:8 
    uint8_t LONG_COND_VALUE_HI        :8;       // 0x85, s:0, e:8 
    uint8_t LONG_ONDELAY_TIME         :8;       // 0x86, s:0, e:8 
    uint8_t LONG_ON_TIME              :8;       // 0x87, s:0, e:8 
    uint8_t LONG_OFFDELAY_TIME        :8;       // 0x88, s:0, e:8 
    uint8_t LONG_OFF_TIME             :8;       // 0x89, s:0, e:8 
    uint8_t LONG_ACTION_TYPE          :4;       // 0x8a, s:0, e:4 
    uint8_t                           :1;       // 0x8a, s:4, e:5 
    uint8_t LONG_MULTIEXECUTE         :1;       // 0x8a, s:5, e:6 
    uint8_t LONG_OFF_TIME_MODE        :1;       // 0x8a, s:6, e:7 
    uint8_t LONG_ON_TIME_MODE         :1;       // 0x8a, s:7, e:8 
    uint8_t LONG_JT_ON                :4;       // 0x8b, s:0, e:4 
    uint8_t LONG_JT_OFF               :4;       // 0x8b, s:4, e:8 
    uint8_t LONG_JT_ONDELAY           :4;       // 0x8c, s:0, e:4 
    uint8_t LONG_JT_OFFDELAY          :4;       // 0x8c, s:4, e:8 
    uint8_t LONG_JT_RAMPON            :4;       // 0x8d, s:0, e:4 
    uint8_t LONG_JT_RAMPOFF           :4;       // 0x8d, s:4, e:8 
    uint8_t                           :5;       // 0x8e, s:0, e:5 
    uint8_t LONG_OFFDELAY_BLINK       :1;       // 0x8e, s:5, e:6 
    uint8_t LONG_ON_LEVEL_PRIO        :1;       // 0x8e, s:6, e:7 
    uint8_t LONG_ONDELAY_MODE         :1;       // 0x8e, s:7, e:8 
    uint8_t LONG_OFF_LEVEL            :8;       // 0x8f, s:0, e:8 
    uint8_t LONG_ON_MIN_LEVEL         :8;       // 0x90, s:0, e:8 
    uint8_t LONG_ON_LEVEL             :8;       // 0x91, s:0, e:8 
    uint8_t LONG_RAMP_START_STEP      :8;       // 0x92, s:0, e:8 
    uint8_t LONG_RAMPON_TIME          :8;       // 0x93, s:0, e:8 
    uint8_t LONG_RAMPOFF_TIME         :8;       // 0x94, s:0, e:8 
    uint8_t LONG_DIM_MIN_LEVEL        :8;       // 0x95, s:0, e:8 
    uint8_t LONG_DIM_MAX_LEVEL        :8;       // 0x96, s:0, e:8 
    uint8_t LONG_DIM_STEP             :8;       // 0x97, s:0, e:8 
    uint8_t LONG_OFFDELAY_STEP        :8;       // 0x98, s:0, e:8 
    uint8_t LONG_OFFDELAY_NEWTIME     :8;       // 0x99, s:0, e:8 
    uint8_t LONG_OFFDELAY_OLDTIME     :8;       // 0x9a, s:0, e:8 
    uint8_t LONG_ELSE_ACTION_TYPE     :4;       // 0xa6, s:0, e:4 
    uint8_t                           :1;       // 0xa6, s:4, e:5 
    uint8_t LONG_ELSE_MULTIEXECUTE    :1;       // 0xa6, s:5, e:6 
    uint8_t LONG_ELSE_OFF_TIME_MODE   :1;       // 0xa6, s:6, e:7 
    uint8_t LONG_ELSE_ON_TIME_MODE    :1;       // 0xa6, s:7, e:8 
    uint8_t LONG_ELSE_JT_ON           :4;       // 0xa7, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFF          :4;       // 0xa7, s:4, e:8 
    uint8_t LONG_ELSE_JT_ONDELAY      :4;       // 0xa8, s:0, e:4 
    uint8_t LONG_ELSE_JT_OFFDELAY     :4;       // 0xa8, s:4, e:8 
    uint8_t LONG_ELSE_JT_RAMPON       :4;       // 0xa9, s:0, e:4 
    uint8_t LONG_ELSE_JT_RAMPOFF      :4;       // 0xa9, s:4, e:8 
};  // 60 byte 


//=============================================================================================================================

//- ----------------------------------------------------------------------------------------------------------------------
//- first time and regular start functions -------------------------------------------------------------------------------

void everyTimeStart(void) {
	// place here everything which should be done on each start or reset of the device
	// typical use case are loading default values or user class configurations

	// init the homematic framework
	hm.confButton.config(2, CONFIG_KEY_PCIE, CONFIG_KEY_INT);           // configure the config button, mode, pci byte and pci bit
	hm.ld.init(2, &hm);                                                 // set the led
	hm.ld.set(welcome);                                                 // show something
	hm.bt.set(30, 3600000);                                             // set battery check, internal, 2.7 reference, measurement each hour
	hm.pw.setMode(4);                                                   // set power management mode

     // register user modules
    cmSwitch[0].regInHM(1, 3, &hm);                                    // register user module
    cmSwitch[0].config(&initIt, &switchIt2);                          // configure user module

    cmSwitch[1].regInHM(2, 3, &hm);                                    // register user module
    cmSwitch[1].config(&initIt, &switchIt2);                          // configure user module 
    
     // register user modules
    cmSwitch[2].regInHM(3, 3, &hm);                                    // register user module
    cmSwitch[2].config(&initIt, &switchIt2);                          // configure user module

    cmSwitch[3].regInHM(4, 3, &hm);                                    // register user module
    cmSwitch[3].config(&initIt, &switchIt2);                          // configure user module 
    
    cmSwitch[4].regInHM(5, 3, &hm);                                    // register user module
    cmSwitch[4].config(&initIt, &switchIt2);                          // configure user module 
    
    cmSwitch[5].regInHM(6, 3, &hm);                                    // register user module
    cmSwitch[5].config(&initIt, &switchIt2);                          // configure user module 
    
/*    
    // register user modules
    cmDimmer[0].regInHM(1, 3, &hm);                                    // register user module
    cmDimmer[0].config(&initIt, &switchIt, &bTemperature);                          // configure user module

    cmDimmer[1].regInHM(2, 3, &hm);                                    // register user module
    cmDimmer[1].config(&initIt, &switchIt, &bTemperature);                          // configure user module

/*
    cmDimmer[2].regInHM(3, 3, &hm);                                    // register user module
    cmDimmer[2].config(&initIt, &switchIt, &bTemperature);                          // configure user module

    cmDimmer[3].regInHM(4, 3, &hm);                                    // register user module
    cmDimmer[3].config(&initIt, &switchIt, &bTemperature);                          // configure user module

    cmDimmer[4].regInHM(5, 3, &hm);                                    // register user module
    cmDimmer[4].config(&initIt, &switchIt, &bTemperature);                          // configure user module

    cmDimmer[5].regInHM(6, 3, &hm);                                    // register user module
    cmDimmer[5].config(&initIt, &switchIt, &bTemperature);                          // configure user module
*/
}

void firstTimeStart(void) {
	// place here everything which should be done on the first start or after a complete reset of the sketch
	// typical use case are default values which should be written into the register or peer database

}
